name: Auto Sync

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto sync changes"
          git pushgit add .github/workflows/auto-sync.yml
          git commit -m "Set up auto-sync workflow"
          git pushname: Auto Sync
          
          on:
            push:
              branches:
                - main
            schedule:
              - cron: '*/30 * * * *'  # Runs every 30 minutes
          
          jobs:
            sync:
              runs-on: ubuntu-latest
              steps:
                - uses: actions/checkout@v2
                  with:
                    fetch-depth: 0
                
                - name: Push changes
                  run: |
                    git config --global user.name 'GitHub Action'
                    git config --global user.email 'action@github.com'
                    git add .
                    git diff --quiet && git diff --staged --quiet || git commit -m "Auto sync changes"
                    git push